---
title: "MED7_Analysis"
output: 
  pdf_document: default
  html_document: default
  github_document: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(skimr)
library(stringr)
library(corrplot)
library(RColorBrewer)
library("PerformanceAnalytics")
library("Hmisc")
library(Rmisc)
library(lubridate)
library(ggbeeswarm)
library(GGally)
library(effsize)
library(magrittr)
library(dplyr)
library(reticulate)
library(raster)
library(sf)
library(TTR)
library(RHRV)
library(corrplot)
library(Hmisc)
library(caret)
library(data.table)
library(viridis)
library(hrbrthemes)
library(eyetrackingR)

library("devtools")
install_github("tmalsburg/saccades/saccades", dependencies=TRUE, force=TRUE)
library(saccades)
```

```{python Loading packages, include=FALSE}
import numpy as np
import pandas as pd
import pandas as pd
pd.options.mode.chained_assignment = None 
import matplotlib.pyplot as plt
from scipy import stats as sc
import sklearn
import biosppy
import matplotlib
import nolds
import hrvanalysis as hrv
```

```{r logData, echo=FALSE,message=F, warning=F,results='hide', include=F}
df_questionnaire <- read.table("Questionnaire_data.csv", header=TRUE, fill = FALSE, sep=",")

p21 <- read.table("Neglect_MED7exp_P21_Physio.csv", header=TRUE, fill = FALSE, sep=",")
names(p21)[names(p21) == "ï..TimeStamp"] <- "Timestamp"  
test <- p21$Timestamp
test <- as_datetime(test, format="%m/%d/%Y %H:%M:%S")
p21$Timestamp <- test
p21$file_path = "21"
p21 <- p21 %>% dplyr::select(file_path, Timestamp, Email, Comment, PID, Millis, EDA, IBI, RawPulse, Pressure, Button)

df_physiological <- list.files(path = "./MED7 Eval data Physiological", full.names = T) %>%

map_dfr(read_csv, .id = "file_path") %>%
group_by(file_path) %>%
dplyr::mutate(ParticipantID = group_indices())
names(df_physiological)[names(df_physiological) == "TimeStamp"] <- "Timestamp"  

df_physiological <- rbind(df_physiological, p21)

df_physiological <- df_physiological %>% mutate(
                    minute = minute(Timestamp),
                    second = second(Timestamp))


df_sample <- list.files(recursive = TRUE, path = "./MED7 testLogs", pattern = "Sample.csv",full.names = T) %>%

map_dfr(read_csv, .id = "file_path") %>%
group_by(file_path) %>%
dplyr::mutate(ParticipantID = group_indices())
df_sample <- df_sample %>% mutate(
                    minute = minute(Timestamp),
                    second = second(Timestamp))
df_sample <- df_sample %>% dplyr::select(-Framecount, -SessionID, -Email, -Event, -ParticipantID)
#df_sample[df_sample == 'NULL'] <- NA


df_event <- list.files(recursive = TRUE, path = "./MED7 testLogs", pattern = "Event.csv",full.names = T) %>%

map_dfr(read_csv, .id = "file_path") %>%
group_by(file_path) %>%
dplyr::mutate(ParticipantID = group_indices())
df_event <- df_event %>% mutate(
                    minute = minute(Timestamp),
                    second = second(Timestamp))
df_event <- df_event %>% dplyr::select(-Framecount, -SessionID, -Email, -ParticipantID)
#df_event[df_event == 'NULL'] <- NA

df_pupil <- list.files(recursive = TRUE, path = "./MED7 testLogs", pattern = "pupil",full.names = T) %>%
map_dfr(read_csv, .id = "file_path") %>%
group_by(file_path) %>%
dplyr::mutate(ParticipantID = group_indices())

pupil_summary <- df_pupil %>% dplyr::select(file_path, diameter, diameter_3d, pupil_timestamp)

#df_event[df_event == 'NULL'] <- NA

questionnaire_Summary <- df_questionnaire %>% dplyr::group_by(Participant) %>% dplyr::select(-Notes ) %>% na.omit()


physiological_Summary <- df_physiological %>% dplyr::group_by(file_path) %>% dplyr::select(file_path, EDA, IBI, Timestamp, minute, second, -ParticipantID) 



sample_Summary <- df_sample %>% dplyr::group_by(file_path)

event_Summary <- df_event %>% dplyr::group_by(file_path) %>% dplyr::select(-TestId, -PlayedPattern)

rm(df_questionnaire, df_physiological, df_sample, df_event, df_pupil, test, p21)
#dfSummary <-  dfSummary %>% merge(dsSummary, by = "Participant", all = T)
```

```{r Pre-processing of Performance, echo=FALSE,message=F, warning=F,results='hide', include=F}
#Performance table for overview
Performance <- table(event_Summary$Event,  event_Summary$file_path)
Performance = t(Performance)
Performance <- as.data.frame.matrix(Performance)

#Added performance from the Event column to event_Summary
#https://www.marsja.se/r-add-column-to-dataframe-based-on-other-columns-conditions-dplyr/
#TODO For loop this
#Performance_columns <- c('SpawnedMole', 'SpawnedFakeMole', 'Shots', 'Misses', 'Hits', 'RedHit', 'Mole_Expired', 'Fake_Mole_Expired')
#Column_data <- c('Mole Spawned', 'Fake Mole Spawned', 'Pointer Shoot', 'Mole Missed', 'Mole Hit', 'Fake Mole Hit', 'Mole Expired', 'Fake Mole Expired')

#for (i in 1:length(Performance_columns))
#  for (j in 1:length(Column_data))
#    event_Summary <- event_Summary %>% mutate(Performance_columns[i] <-  case_when(Event == Column_data[j] ~ 1))

#spawns
event_Summary <- event_Summary %>% mutate(SpawnedMole =  case_when(Event == 'Mole Spawned' ~ 1))
event_Summary <- event_Summary %>% mutate(SpawnedFakeMole =  case_when(Event == 'Fake Mole Spawned' ~ 1))
#Shots
event_Summary <- event_Summary %>% mutate(Shots =  case_when(Event == 'Pointer Shoot' ~ 1))
#Hit and misses
event_Summary <- event_Summary %>% mutate(Misses =  case_when(Event == 'Mole Missed' ~ 1))
event_Summary <- event_Summary %>% mutate(Hits =  case_when(Event == 'Mole Hit' ~ 1))
event_Summary <- event_Summary %>% mutate(RedHit =  case_when(Event == 'Fake Mole Hit' ~ 1))
#Expired mole
event_Summary <- event_Summary %>% mutate(Mole_Expired =  case_when(Event == 'Mole Expired' ~ 1))
event_Summary <- event_Summary %>% mutate(Fake_Mole_Expired =  case_when(Event == 'Fake Mole Expired' ~ 1))
event_Summary <- event_Summary %>% replace(is.na(.), 0)
event_Summary <- event_Summary %>% replace(is.null(.), 0)

#event_Summary <- event_Summary %>% filter(Event == c('Mole Spawned', 'Fake Mole Spawned', 'Pointer Shoot' , 'Mole Missed', 'Mole Hit', 'Fake Mole Hit', 'Mole Expired', 'Fake Mole Expired'))
event_Summary <- event_Summary %>% filter(Event != "Wall Size Update", Event != "MotorSpace Size Update", Event != "CountDown 3", Event != "CountDown 2",Event !=  "CountDown 1", Event != "Controller Offset Set 0", Event !=  "CountDown 0", Event !=  "Prism Offset Set 0")

```

```{r Compiling event data for sliding window, echo=FALSE,message=F, warning=F,results='hide', include=F}
event_data <- event_Summary %>% dplyr::group_by(file_path) %>% dplyr::select(SpawnedMole, SpawnedFakeMole, Shots, Misses, Hits, RedHit, Mole_Expired,  Fake_Mole_Expired, file_path, Timestamp, minute, second, MoleActivatedDuration)

event_data <- event_data %>% replace(is.na(.), 0)
event_data <- event_data %>% replace(is.null(.), 0)
event_data$MoleActivatedDuration[event_data$MoleActivatedDuration == "NULL"] <- 0
event_data$MoleActivatedDuration[event_data$MoleActivatedDuration == "5.0000"] <- 0

rm(event_Summary)
```

```{r Pre-processing of physiological logs, echo=FALSE,message=F, warning=F,results='hide', include=F}
physio_DF <- filter(physiological_Summary, IBI > -1 & IBI > 401 & IBI <= 1200)

physio_DF <- physio_DF %>% group_by(file_path) %>% mutate(SmoothedEDA = runMean(EDA, 5))

#computing the mean for each NA value
physio_DF$SmoothedEDA[is.na(physio_DF$SmoothedEDA)]<-mean(physio_DF$SmoothedEDA, na.rm = T)
physio_DF[physio_DF == 0] <- NA
physio_DF <- physio_DF %>% dplyr::group_by(file_path) %>% dplyr::select(-minute, -second)#, -Timestamp

rm(physiological_Summary)
```

```{r pupil data pre-process, echo=FALSE,message=F, warning=F,results='hide', include=F}
pupil_data <- pupil_summary %>% dplyr::group_by(file_path)
pupil_data[is.na(pupil_data)] <- 0.0000
pupil_data <- sapply(pupil_data, as.double)

pupil_data <- data.frame(pupil_data)


pupil_data["pupil_timestamp"] <- round(pupil_data$pupil_timestamp)
pupil_data <- pupil_data %>% filter(diameter < 101)

pup_data_filtered <- pupil_data %>% filter(file_path == 21)
ggplot(data = pup_data_filtered, aes(x = pupil_timestamp, y = diameter))+
    geom_smooth(aes())+ geom_point() + theme_minimal()

pupilmean <- pupil_data %>% group_by(file_path, pupil_timestamp) %>% mutate_each(funs(mean)) %>% distinct
pupilmax <- pupil_data %>% group_by(file_path, pupil_timestamp) %>% mutate_each(funs(max)) %>% distinct
pupilsd <- pupil_data %>% group_by(file_path, pupil_timestamp) %>% mutate_each(funs(sd)) %>% distinct

pupilmean <- pupilmean %>%
  dplyr::rename(
    mean_diameter = diameter,
    mean_diameter_3d = diameter_3d
  )

pupilmax <- pupilmax %>%
  dplyr::rename(
    max_diameter = diameter,
    max_diameter_3d = diameter_3d
  )

pupilsd <- pupilsd %>%
  dplyr::rename(
    sd_diameter = diameter,
    sd_diameter_3d = diameter_3d
  )



pupiltest <- pupil_data %>% group_by(file_path) %>% distinct(pupil_timestamp)
pupiltest <- pupiltest %>% left_join(pupilmean, by = c("file_path", "pupil_timestamp"))
pupiltest <- pupiltest %>% left_join(pupilmax, by = c("file_path", "pupil_timestamp"))
pupiltest <- pupiltest %>% left_join(pupilsd, by = c("file_path", "pupil_timestamp"))

pup_data_filtered <- pupiltest %>% filter(file_path == 21)
ggplot(data = pup_data_filtered, aes(x = pupil_timestamp, y = mean_diameter))+ geom_point() + theme_minimal()

rm(pupilmean, pupilmax, pupilsd)
```

```{r sccades and velocity, echo=FALSE,message=F, warning=F,results='hide', include=F}

attempt <- sample_Summary %>% dplyr::select(file_path, contains("WorldGazeHitPosition"), Timestamp)

attempt$Timestamp = as.numeric(ave(attempt$WorldGazeHitPositionX, attempt$file_path, FUN = seq_along))

attempt <- attempt %>%
  summarise(x= as.numeric(WorldGazeHitPositionX),
            y= as.numeric(WorldGazeHitPositionY),
            trial = file_path,
            time= Timestamp)

fix <- detect.fixations(attempt)
head(fix)
```

```{r Hand tracking data, echo=FALSE,message=F, warning=F,results='hide', include=F}
right.df <- data.frame( x = sample_Summary$RightControllerPosWorldX,
y = sample_Summary$RightControllerPosWorldY,
z = sample_Summary$RightControllerPosWorldZ,
group = sample_Summary$file_path)
right.df <- st_as_sf(right.df,coords = c("x","y","z"),remove = F)
right.df <- right.df %>%
  group_by(group) %>%
  dplyr::mutate(
    lead = geometry[(dplyr::row_number()) + 1],
    dist = st_distance(geometry, lead, by_element = T),
  )
sample_Summary$righthanddist <- right.df$dist

left.df <- data.frame( x = sample_Summary$LeftControllerPosTravelX,
y = sample_Summary$LeftControllerPosWorldY,
z = sample_Summary$LeftControllerPosWorldZ,
group = sample_Summary$file_path)
left.df <- st_as_sf(left.df,coords = c("x","y","z"),remove = F)
left.df <- left.df %>%
  group_by(group) %>%
  dplyr::mutate(
    lead = geometry[(dplyr::row_number()) + 1],
    dist = st_distance(geometry, lead, by_element = T),
  )
sample_Summary$lefthanddist <- left.df$dist

rm(right.df, left.df)
```

```{r Head tracking data, echo=FALSE,message=F, warning=F,results='hide', include=F}
head.df <- data.frame( x = sample_Summary$HeadCameraPosWorldX,
y = sample_Summary$HeadCameraPosWorldY,
z = sample_Summary$HeadCameraPosWorldZ,
group = sample_Summary$file_path)

head.df <- st_as_sf(head.df,coords = c("x","y","z"),remove = F)

head.df <- head.df %>%
  group_by(group) %>%
  dplyr::mutate(
    lead = geometry[(dplyr::row_number()) + 1],
    dist = st_distance(geometry, lead, by_element = T),
  )

sample_Summary$headdist <- head.df$dist


headrot.df <- data.frame( x = sample_Summary$HeadCameraRotEulerX,
y = sample_Summary$HeadCameraRotEulerY,
z = sample_Summary$HeadCameraRotEulerZ,
group = sample_Summary$file_path)

headrot.df <- st_as_sf(headrot.df,coords = c("x","y","z"),remove = F)

headrot.df <- headrot.df %>%
  group_by(group) %>%
  dplyr::mutate(
    lead = geometry[(dplyr::row_number()) + 1],
    dist = st_distance(geometry, lead, by_element = T),
  )
dist <- ifelse((!is.na(headrot.df$dist) & headrot.df$dist > 100), (360 - headrot.df$dist), (headrot.df$dist))
dist[is.na(dist)] <- 0
dist <- ifelse((headrot.df$dist < 0 & headrot.df$dist > 100), (0), (headrot.df$dist))
dist[is.na(dist)] <- 0
sample_Summary$headrot <- dist

rm(head.df, headrot.df)
```

```{r eye tracking data, echo=FALSE,message=F, warning=F,results='hide', include=F}
eye_data <- sample_Summary %>% dplyr::group_by(file_path) %>% dplyr::select(GazeConfidence, WorldGazeHitPositionX, WorldGazeHitPositionY, WorldGazeHitPositionZ)
eye_data[eye_data == "NULL"] <- "0.0000"
eye_data$Timestamp <- sample_Summary$Timestamp
eye_data[, 2:5] <- sapply(eye_data[, 2:5], as.double)

eye_data <- st_as_sf(eye_data,coords = c("WorldGazeHitPositionX","WorldGazeHitPositionY","WorldGazeHitPositionZ"),remove = F)
eye_data <- eye_data %>%
  group_by(file_path) %>%
  dplyr::mutate(
    lead = geometry[(dplyr::row_number()) + 1],
    dist = st_distance(geometry, lead, by_element = T),
  )

sample_Summary$eyedist <- eye_data$dist

rm(eye_data)
```

```{python Sliding for event logs, echo=FALSE,message=F, warning=F,results='hide', include=F}
py_event = r.event_data
py_event_data = pd.DataFrame(py_event)
window = "30s"
py_windowed_events = pd.DataFrame
py_sliding_events = pd.DataFrame

py_event_data["file_path"] = pd.to_numeric(py_event_data["file_path"])
py_event_data.index = pd.to_datetime(py_event_data["Timestamp"])

py_event_data["MoleActivatedDuration"] = pd.to_numeric(py_event_data["MoleActivatedDuration"])

py_windowed_events_mean = py_event_data.groupby("file_path").resample("1s").mean().bfill()
py_windowed_events_mean = py_windowed_events_mean.add_suffix('_mean')
py_windowed_events_mean["file_path"] = py_windowed_events_mean.index.get_level_values(0)
py_windowed_events_mean["Timestamp"] = py_windowed_events_mean.index.get_level_values(1)

py_windowed_events_sum = py_event_data.groupby("file_path").resample("1s").sum()
py_windowed_events_sum = py_windowed_events_sum.add_suffix('_sum')
py_windowed_events_sum["file_path"] = py_windowed_events_sum.index.get_level_values(0)
py_windowed_events_sum["Timestamp"] = py_windowed_events_sum.index.get_level_values(1)

py_sliding_events = pd.merge(py_windowed_events_sum.rename_axis([None, None]), py_windowed_events_mean.rename_axis([None, None]),  how='left', on =["Timestamp", "file_path"])
#py_sliding_events = py_windowed_events
#py_sliding_events = py_windowed_events.set_index("Timestamp").rolling("30s", min_periods = 30).sum()
#py_sliding_events["file_path"] = py_windowed_events.index.get_level_values(0)

py_sliding_events.isnull().sum()

```

```{python Sliding for sample logs, echo=FALSE,message=F, warning=F,results='hide', include=F}
py_sample = r.sample_Summary
py_sample_data = pd.DataFrame(py_sample)
window = "30s"
py_windowed_samples = pd.DataFrame
py_sliding_samples = pd.DataFrame

py_sample_data["file_path"] = pd.to_numeric(py_sample_data["file_path"])
py_sample_data.index = pd.to_datetime(py_sample_data["Timestamp"])

py_windowed_samples_mean = py_sample_data.groupby("file_path").resample("1s").mean()
py_windowed_samples_mean = py_windowed_samples_mean.add_suffix('_mean')
py_windowed_samples_mean["file_path"] = py_windowed_samples_mean.index.get_level_values(0)
py_windowed_samples_mean["Timestamp"] = py_windowed_samples_mean.index.get_level_values(1)

py_windowed_samples_sum = py_sample_data.groupby("file_path").resample("1s").sum()
py_windowed_samples_sum = py_windowed_samples_sum.add_suffix('_sum')
py_windowed_samples_sum["file_path"] = py_windowed_samples_sum.index.get_level_values(0)
py_windowed_samples_sum["Timestamp"] = py_windowed_samples_sum.index.get_level_values(1)

py_windowed_samples_min = py_sample_data.groupby("file_path").resample("1s").min()
py_windowed_samples_min = py_windowed_samples_min.add_suffix('_min')
py_windowed_samples_min["file_path"] = py_windowed_samples_min.index.get_level_values(0)
py_windowed_samples_min["Timestamp"] = py_windowed_samples_min.index.get_level_values(1)

py_windowed_samples_max = py_sample_data.groupby("file_path").resample("1s").max()
py_windowed_samples_max = py_windowed_samples_max.add_suffix('_max')
py_windowed_samples_max["file_path"] = py_windowed_samples_max.index.get_level_values(0)
py_windowed_samples_max["Timestamp"] = py_windowed_samples_max.index.get_level_values(1)

py_sliding_samples = pd.merge(py_windowed_samples_sum.rename_axis([None, None]), py_windowed_samples_mean.rename_axis([None, None]), how='left', on =["Timestamp", "file_path"])
py_sliding_samples = pd.merge(py_sliding_samples, py_windowed_samples_min.rename_axis([None, None]), how='left', on =["Timestamp", "file_path"])
py_sliding_samples = pd.merge(py_sliding_samples, py_windowed_samples_max.rename_axis([None, None]), how='left', on =["Timestamp", "file_path"])
#py_sliding_samples = py_windowed_samples.set_index("Timestamp").rolling("30s", min_periods = 30).sum()
#py_sliding_samples["file_path"] = py_windowed_samples.index.get_level_values(0)

py_sliding_samples.isnull().sum()
```

```{python Sliding for physiological logs, echo=FALSE,message=F, warning=F,results='hide', include=F}
py_physio_DF = r.physio_DF
py_physio_Data = pd.DataFrame(py_physio_DF)
window = "30s"
py_windowed_physio = pd.DataFrame
py_sliding_physio = pd.DataFrame

py_physio_Data = py_physio_Data.assign(max_hr = 0)
py_physio_Data = py_physio_Data.assign(mean_nni = 0)
py_physio_Data = py_physio_Data.assign(median_nni = 0)
py_physio_Data = py_physio_Data.assign(min_hr = 0)
py_physio_Data = py_physio_Data.assign(nni_50 = 0)
py_physio_Data = py_physio_Data.assign(rmssd = 0)
py_physio_Data = py_physio_Data.assign(sdnn = 0)
py_physio_Data = py_physio_Data.assign(pnni_50 = 0)

py_physio_Data["file_path"] = pd.to_numeric(py_physio_Data["file_path"])
py_physio_Data.index = pd.to_datetime(py_physio_Data["Timestamp"])
namearray = ["max_hr","mean_nni","median_nni","min_hr","nni_50","rmssd","sdnn","pnni_50"]

def calc_time(window, name):
  time_domain = hrv.get_time_domain_features(np.array(window))
  return time_domain[name]


test2 = pd.DataFrame(data = None, columns=py_physio_Data.columns)
for s in range(1, 22):
  test = py_physio_Data[py_physio_Data["file_path"] == s]
  for i in namearray:
      test[i] = test["IBI"].rolling("30s", min_periods = 30).apply(func = calc_time, kwargs={'name':i})
  test2 = pd.concat([test2, test])
  
  
py_physio_Data = test2
py_scp_time = test2[test2["file_path"] == 21]

py_physio_Data = py_physio_Data.assign(lf = 0)
py_physio_Data = py_physio_Data.assign(hf = 0)
py_physio_Data = py_physio_Data.assign(lf_hf_ratio = 0)
py_physio_Data = py_physio_Data.assign(lfnu = 0)
py_physio_Data = py_physio_Data.assign(hfnu = 0)
py_physio_Data = py_physio_Data.assign(total_power = 0)
py_physio_Data = py_physio_Data.assign(vlf = 0)
namearray = ["lf","hf","lf_hf_ratio","lfnu","hfnu","total_power","vlf"]

def calc_freq(window, name):
  freq_domain = hrv.get_frequency_domain_features(np.array(window))
  return freq_domain[name]


test2 = pd.DataFrame(data = None, columns=py_physio_Data.columns)
for s in range(1, 22):
  test = py_physio_Data[py_physio_Data["file_path"] == s]
  for i in namearray:
      test[i] = test["IBI"].rolling("30s", min_periods = 30).apply(func = calc_freq, kwargs={'name':i})
  test2 = pd.concat([test2, test])
  
py_physio_Data = test2
#py_physio_Data["EDA"] = py_physio_Data["EDA"].groupby("file_path").rolling(8, min_periods = 8).mean()

py_physio_Data = py_physio_Data.dropna()

py_physio_Data = py_physio_Data.groupby("file_path").resample("1s").mean().bfill()
py_physio_Data["file_path"] = py_physio_Data.index.get_level_values(0)
py_physio_Data["Timestamp"] = py_physio_Data.index.get_level_values(1)


py_physio_Data.isnull().sum()
```

```{r Sliding Window prototype check}
r_event_Window <- py$py_sliding_events
r_sample_Window <- py$py_sliding_samples
r_physio_Window <- py$py_physio_Data

r_sample_Window$Timestamp = row.names(r_sample_Window)
r_sample_Window$Timestamp = ave(r_sample_Window$headdist_sum, r_sample_Window$file_path, FUN = seq_along)
r_sample_Window <- r_sample_Window %>% dplyr::select(Timestamp, file_path, contains("headdist"), contains("eyedist"), contains("righthanddist"), contains("lefthanddist"), contains("headrot"))

r_event_Window$Timestamp = row.names(r_event_Window)
r_event_Window$Timestamp = ave(r_event_Window$Hits_sum, r_event_Window$file_path, FUN = seq_along)

r_physio_Window$Timestamp = row.names(r_physio_Window)
r_physio_Window$Timestamp = ave(r_physio_Window$EDA, r_physio_Window$file_path, FUN = seq_along)

pupiltest$Timestamp = row.names(pupiltest)
pupiltest$Timestamp = ave(pupiltest$mean_diameter, pupiltest$file_path, FUN = seq_along)

ggplot(r_physio_Window,aes(x=Timestamp,y=hf)) + geom_smooth(method = "lm",level = 0.95) + 
geom_point() + facet_wrap(~file_path, nrow = 3, ncol = 7)

```

```{r Overview, echo=FALSE,message=F, warning=F,results='hide', include=F}
sample_Summary %>%
physiological_Summary  %>%
  select(-file_path) %>%
   skim()

#sample_Summary[sample_Summary == "NULL"] <- NA
sample_Summary %>%

  select(-file_path) %>%
   skim()

```

```{r merging and standardizing of DF's, echo=FALSE,message=F, warning=F,results='hide', include=F}
# https://statisticsglobe.com/merge-data-frames-by-two-id-columns-in-r 

# https://statisticsglobe.com/r-dplyr-join-inner-left-right-full-semi-anti
AggDF <- left_join(r_physio_Window, r_sample_Window, by = c("file_path", "Timestamp"))
AggDF <- left_join(AggDF, r_event_Window, by = c("file_path", "Timestamp"))
#AggDF <- AggDF %>% dplyr::select(-minute, -second) %>% na.omit()
AggDF <- AggDF %>%na.omit()

AggDF$file_path <- as.numeric(AggDF$file_path) 

AggDFeven <- AggDF %>% filter(file_path %% 2 == 0)
AggDFeven$condition <- "VE"
AggDFodd <- AggDF %>% filter(file_path %% 2 != 0)
AggDFodd$condition <- "No VE"

gamedf <- rbind(AggDFodd, AggDFeven)
```

```{r save to csv, echo=FALSE,message=F, warning=F,results='hide', include=F}
pupiltest$file_path <- as.numeric(pupiltest$file_path )
gamedf <- left_join(gamedf, pupiltest, by = c("file_path", "Timestamp"))
gamedf$righthanddist[gamedf$file_path == 14] <- gamedf$lefthanddist[gamedf$file_path == 14]

gamedf <- gamedf %>% dplyr::select(-pupil_timestamp, -headdist_min, -contains("lefthand"), -contains("FakeMole"), -contains("minute"), -contains("second"), -file_path_mean, -minute_mean, -second_mean, -contains("Fake_Mole"), -file_path_sum, -contains("nni"), -total_power, -vlf, -contains("Red"))


write.csv(gamedf, "processed_data.csv", row.names = F)
```

```{r correlation checks, include=FALSE}
corrstuff <- gamedf %>% dplyr::select(-Timestamp, -condition, -file_path)
corMatMy <- cor(corrstuff)
corrplot(corMatMy, order = "hclust", tl.cex = 0.6)
highlyCor <- colnames(gamedf)[findCorrelation(corMatMy, cutoff = 0.9, verbose = TRUE)]
gamedf_corr <- gamedf[, which(!colnames(gamedf) %in% highlyCor)]
```

```{r Parition data, include=FALSE}
VE_label <- "Y"
noVE_label <- "N"

VE <- df_questionnaire %>% filter(VE==VE_label)
noVE <- df_questionnaire %>% filter(VE==noVE_label)
```

```{r Does our counterbalancing work?}
wilcox.test(VE$M1, noVE$M1, paired = F)
wilcox.test(VE$M2, noVE$M2, paired = F)
wilcox.test(VE$M3, noVE$M3, paired = F)
wilcox.test(VE$M4, noVE$M4, paired = F)
wilcox.test(VE$M5, noVE$M5, paired = F)
wilcox.test(VE$M6, noVE$M6, paired = F)
wilcox.test(VE$M7, noVE$M7, paired = F)
wilcox.test(VE$M8, noVE$M8, paired = F)
wilcox.test(VE$M9, noVE$M9, paired = F)
wilcox.test(VE$M10, noVE$M10, paired = F)
wilcox.test(VE$M11, noVE$M11, paired = F)
```

```{r Wilcoxon test on questionnaire}
wilcox.test(VE$Q1, noVE$Q1, paired = F)
wilcox.test(VE$Q2, noVE$Q2, paired = F)
wilcox.test(VE$Q3, noVE$Q3, paired = F)
wilcox.test(VE$Q4, noVE$Q4, paired = F)
wilcox.test(VE$Q5, noVE$Q5, paired = F)
wilcox.test(VE$Q6, noVE$Q6, paired = F)
wilcox.test(VE$Q7, noVE$Q7, paired = F)
wilcox.test(VE$Q8, noVE$Q8, paired = F)
wilcox.test(VE$Q9, noVE$Q9, paired = F)
wilcox.test(VE$Q10, noVE$Q10, paired = F)
wilcox.test(VE$Q11, noVE$Q11, paired = F)
wilcox.test(VE$Q12, noVE$Q12, paired = F)
wilcox.test(VE$Q13, noVE$Q13, paired = F)
```

```{r Correlation Tests}
filter_out = c(1, 2, 3, 4, 5, 6, 7, 8, 34) 
chart.Correlation(df_questionnaire[,-filter_out], histogram=FALSE, pch=19)
# Data for per-condition correlation matrix among all of our variables
correlationMatrix <- Hmisc::rcorr(as.matrix(df_questionnaire[,-filter_out]))
#correlationMatrix <- flattenCorrMatrix(correlationMatrix$r, correlationMatrix$P)
# Per-condition correlation matrix among all of our variables
for(condition in unique(df_questionnaire$Condition)) {
  print(condition)
  corrplot(cor(df_questionnaire[df_questionnaire$VE==VE,-filter_out]), type="upper",col=brewer.pal(n=8, name="RdYlBu"))
}
print("Both Conditions")
corrplot(cor(df_questionnaire[-filter_out]), type="upper",col=brewer.pal(n=8, name="RdYlBu"))
         
corMatMy <- cor(df_questionnaire[9:33])
highlyCor <- colnames(df_questionnaire)[findCorrelation(corMatMy, cutoff = 0.5, verbose = TRUE)]

corMatMy <- cor(df_questionnaire[9:33])
corrplot(corMatMy, order = "hclust", tl.cex = 0.7)
highlyCor <- colnames(df_questionnaire)[findCorrelation(corMatMy, cutoff = 0.5, verbose = TRUE)]
bc_data_cor <- df_questionnaire[, which(!colnames(df_questionnaire) %in% highlyCor)]

df_questionnaire <- df_questionnaire %>% dplyr::select(-Notes)
questionnaire.pca <- prcomp(df_questionnaire[9:33], center=TRUE, scale=TRUE)
plot(questionnaire.pca, type="l", main='')
grid(nx = 10, ny = 14)
title(main = "Principal components weight", sub = NULL, xlab = "Components")
box()
summary(questionnaire.pca)
pca_var <- questionnaire.pca$sdev^2
pve_df <- pca_var / sum(pca_var)
cum_pve <- cumsum(pve_df)
pve_table <- tibble(comp = seq(13:ncol(df_questionnaire %>% dplyr::select(-VE))), pve_df, cum_pve)
ggplot(pve_table, aes(x = comp, y = cum_pve)) + 
  geom_point() + 
  geom_abline(intercept = 0.95, color = "red", slope = 0) + theme_minimal()
pca_df <- as.data.frame(questionnaire.pca$x)
ggplot(pca_df, aes(x=PC1, y=PC2, col=df_questionnaire$VE)) + geom_point(alpha=0.5)

bc_data_cor2 <- bc_data_cor[7:25]
questionnaire.pca2 <- prcomp(bc_data_cor2, center=TRUE, scale=TRUE)
summary(questionnaire.pca2)
pca_var2 <- questionnaire.pca2$sdev^2
pve_df2 <- pca_var2 / sum(pca_var2)
cum_pve2 <- cumsum(pve_df2)
pve_table2 <- tibble(comp = seq(1:ncol(bc_data_cor2)), pve_df2, cum_pve2)
ggplot(pve_table2, aes(x = comp, y = cum_pve2)) + 
  geom_point() + 
  geom_abline(intercept = 0.95, color = "red", slope = 0)
pca2_df <- as.data.frame(questionnaire.pca2$x)
ggplot(pca2_df, aes(x=PC1, y=PC2, col=df_questionnaire$VE)) + geom_point(alpha=0.5)
```

